services:
  mqtt:
    image: docker.io/eclipse-mosquitto
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ./configs/mosquitto.conf:/mosquitto/config/mosquitto.conf
  db:
    image: docker.io/postgres
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    secrets: 
      - db_password
    ports:
      - 5432:5432
    healthcheck:
      test: "psql postgres://postgres:$(cat $POSTGRES_PASSWORD_FILE)@localhost:5432 || exit 1"
      start_period: 20s
      interval: 5s
      retries: 5
  adminer:
    image: docker.io/adminer
    ports:
      - 8080:8080
  migrations:
    image: ingest
    command: "sqlx database setup"
    depends-on:
      db:
        condition: service_healthy
        restart: true
  ingest:
    build: ./ingest/.
    image: ingest
    command: ingest > /logs/ingest.log
    restart: on-failure
    volumes:
      - ./logs:/logs
    depends-on:
      db:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully

secrets:
  db_password:
    file: ./configs/db_password.txt
