# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-4.5.1

# NOTE: The namespace sharing for a pod has been modified by the user and is not the same as the
# default settings for kubernetes. This can lead to unexpected behavior when running the generated
# kube yaml in a kubernetes cluster.
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2023-07-09T00:05:23Z"
  labels:
    app: iot-dash
  name: iot-dash
spec:
  containers:
  - name: mqtt
    args:
    - /usr/sbin/mosquitto
    - -c
    - /mosquitto/config/mosquitto.conf
    image: docker.io/library/eclipse-mosquitto:latest
    ports:
    - containerPort: 1883
      hostPort: 1883
    - containerPort: 9001
      hostPort: 9001
    volumeMounts:
    - mountPath: /mosquitto/config/mosquitto.conf
      name: home-zdelv-iot_dash-configs-mosquitto.conf-host-0
    - mountPath: /mosquitto/log
      name: ed7393126f96d02f2f718d8ee3fd28e8e922afce9cb4fb9e0ad1de56b9a8d65e-pvc
    - mountPath: /mosquitto/data
      name: 00545328ac13e10e1cf47bb3df4085ebcfbcf4b5ab6bfbea27b7e49e6b84fea0-pvc
  - name: db
    args:
    - postgres
    env:
    - name: POSTGRES_PASSWORD_FILE
      value: /run/secrets/db_password
    image: docker.io/library/postgres:latest
    ports:
    - containerPort: 5432
      hostPort: 5432
    volumeMounts:
    - mountPath: /run/secrets/db_password
      name: home-zdelv-iot_dash-configs-db_password.txt-host-0
      readOnly: true
    # - mountPath: /var/lib/postgresql/data
    #   name: c0f1466f8821480ed73dbb723cf339fb73bdeba534b0562a74b08d7a41b532ae-pvc
    - mountPath: /docker-entrypoint-initdb.d
      name: database-init
  - name: adminer
    args:
    - php
    - -S
    - '[::]:8080'
    - -t
    - /var/www/html
    image: docker.io/library/adminer:latest
    ports:
    - containerPort: 8080
      hostPort: 8080
    securityContext: {}
#   - name: migrations
#     command:
#     - sqlx
#     - database
#     - setup
#     image: localhost/ingest:latest
#     volumeMounts:
#     - mountPath: /logs
#       name: home-zdelv-iot_dash-logs-host-0
  - name: ingest
    command:
    - ingest
    - '>'
    - /logs/ingest.log
    image: localhost/ingest:latest
    volumeMounts:
    - mountPath: /logs
      name: home-zdelv-iot_dash-logs-host-0
  volumes:
  - hostPath:
      path: ./configs/db
      type: Directory
    name: database-init
  - hostPath:
      path: /home/zdelv/iot_dash/logs
      type: Directory
    name: home-zdelv-iot_dash-logs-host-0
  - hostPath:
      path: /home/zdelv/iot_dash/configs/mosquitto.conf
      type: File
    name: home-zdelv-iot_dash-configs-mosquitto.conf-host-0
  - name: ed7393126f96d02f2f718d8ee3fd28e8e922afce9cb4fb9e0ad1de56b9a8d65e-pvc
    persistentVolumeClaim:
      claimName: ed7393126f96d02f2f718d8ee3fd28e8e922afce9cb4fb9e0ad1de56b9a8d65e
  - name: 00545328ac13e10e1cf47bb3df4085ebcfbcf4b5ab6bfbea27b7e49e6b84fea0-pvc
    persistentVolumeClaim:
      claimName: 00545328ac13e10e1cf47bb3df4085ebcfbcf4b5ab6bfbea27b7e49e6b84fea0
  - hostPath:
      path: /home/zdelv/iot_dash/configs/db_password.txt
      type: File
    name: home-zdelv-iot_dash-configs-db_password.txt-host-0
  - name: c0f1466f8821480ed73dbb723cf339fb73bdeba534b0562a74b08d7a41b532ae-pvc
    persistentVolumeClaim:
      claimName: c0f1466f8821480ed73dbb723cf339fb73bdeba534b0562a74b08d7a41b532ae

